Mapping rules; fixes #37
RHEAGROUP/DEH-CATIA pull request #44
Opened 2021-06-15 14:33 UTC by nathanatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEH-CATIA/pulls) open
- [x] I have verified that I am following the DEH-CATIA [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEH-CATIA/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

- [x] Implemented the rule that handles mapping from 10-25 to Catia
    - [x] Mapping of parameters
    - [x] Mapping of Position and Orientation
    - [x] Mapping of new Catia Element
- [x] Added a WIP of the CatiaShapeTemplateService
- [x] Added some unit test

2021-06-15 14:34 UTC, nathanatrhea commented
![image](https://user-images.githubusercontent.com/61700723/122071980-7d6f6280-cdf7-11eb-8eca-c8a640f74e27.png)

2021-06-17 08:06 UTC, lxatrhea requested changes
Some cosmetic things and some suggestions about the hardest part of our jobs as software developer: Creating consistent and understandable method / variable names.

2021-06-17 08:06 UTC, lxatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +        private bool CreateCatiaElement(MappedElementRowViewModel mappedElementRowViewModel)
Always a nice discussion ;) 
Imho a "create" method should be a void, or return the created object when you're sure the object will always be created.
This method returns a bool which probably means that it will return false if an object could not be created.
I always like the way of naming these kind of methods to **Try**BlaBlaBla. 
Then it is (more) clear at the code where the method is called that things could go wrong during object creation.

2021-06-17 08:06 UTC, lxatrhea commented on DEHCATIA/Services/CatiaTemplateService/CatiaTemplateService.cs
> +//    This file is part of DEHPEcosimPro
Ecosim?

2021-06-17 08:06 UTC, lxatrhea commented on DEHCATIA/Services/ComConnector/CatiaComService.cs
> +            //var arrayOftransformation = element.HubElement.
No uncommented code == remove method?

2021-06-17 08:52 UTC, nathanatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +                    var errorMessage = $"The value {value} from Parameter {parameter.ModelCode()} could not be parsed as {typeof(TValueType).Name}";
me too but in this case nameof(TValueType) = "TValueType"

2021-06-17 08:53 UTC, nathanatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +                    var errorMessage = $"The value {value} from Parameter {parameter.ModelCode()} could not be parsed as Enum {typeof(TEnum).Name}";
same as above

2021-06-17 09:23 UTC, lxatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +                    var errorMessage = $"The value {value} from Parameter {parameter.ModelCode()} could not be parsed as {typeof(TValueType).Name}";
You're right about that one, but I meant the Parameter class: nameof(Parameter)

2021-06-17 09:23 UTC, lxatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +                    var errorMessage = $"The value {value} from Parameter {parameter.ModelCode()} could not be parsed as Enum {typeof(TEnum).Name}";
same as above ;)

2021-06-17 09:36 UTC, nathanatrhea commented on DEHCATIA.Tests/MappingRules/ElementToCatiaRuleTestFixture.cs
> +//    This file is part of DEHPEcosimPro
Well spotted, resolved as well as many more

2021-06-17 09:55 UTC, lxatrhea approved these changes

2021-06-18 14:16 UTC, samatrhea approved these changes
looks good to me, only comment is on dependency injection and the fact that the rules are hard-coded

2021-06-18 14:16 UTC, samatrhea commented on DEHCATIA/MappingRules/ElementToCatiaRule.cs
> +        private readonly IHubController hubController = AppContainer.Container.Resolve<IHubController>();
any particular reason these are not just property injected?

2021-06-18 14:44 UTC, merged